url: https://captainproton42.github.io

# Build settings
remote_theme: captainproton42/protontheme
plugins:
 - jekyll-remote-theme

title: John Wigg
subtitle:
  SciComp Student // Hobbyist Gamedev

navbar-links:
  About me : "/#subtitle"
  Projects: "/#posts"
  Résumé: "resume"

social:
  twitter: captainproton42
  github: captainproton42
  reddit: captainproton42
  itchio: captainproton42
  linkedin: john-wigg

page-theme: yellow-candy

openInfoBox: "<div markdown='1' class='infobox'>"
closeInfoBox: "</div>"
openInfoBoxTitle: "<div class='infobox-title'>"
closeInfoBoxTitle: "</div>"

beginFigure: "<div markdown='1' class='figure'>"
endFigure: "</div>"
beginCaption: "<p markdown='1' class='figure-caption'>"
endCaption: "</p>"
